name: Tests

on:
  push:
    branches: [main, issue*]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit & E2E Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'mysql://user:password@localhost:3306/testdb'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Run unit tests
        run: yarn test --coverage
      - name: Start Docker Daemon(for Test Containers)
        run: |
          sudo systemctl start docker
          sudo chmod 666 /var/run/docker.sock

      - name: Upload coverage reports
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
